-- ============================================================
-- KLAP CORE — Release Watchdog (SIN SEED DE DEMO)
-- ============================================================
-- El sistema opera SOLO con datos reales. No se siembra ningún
-- release de ejemplo: el primer release se crea en producción
-- desde Release Analyzer → "Crear en Watchdog" cuando llega el
-- primer Release Note real de BPC.
--
-- Este archivo se dejó vacío a propósito. Antes contenía un
-- release de prueba (R26.60 con UUID c1b2c3d4-...0001) que se usó
-- durante el desarrollo del módulo; esos datos fueron eliminados
-- de Neon al dejar el sistema operativo (ver neon/cleanup_demo_data.sql).
--
-- El esquema se crea con schema_release_watchdog.sql.
-- NO EJECUTAR ningún INSERT de ejemplo aquí.
-- ============================================================
